models:
  - name: posts_questions
    description: "Table with data about posts questions"
    columns:
      - name: id
        description: "Unique ID of the question."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the question."
      - name: body
        description: "Content of the question."
      - name: accepted_answer_id
        description: "ID of the accepted answer, if any."
      - name: answer_count
        description: "Number of answers to the post question."
      - name: comment_count
        description: "Number of comments on the post question."
      - name: community_owned_date
        description: "Timestamp when the post became community-owned."
      - name: creation_date
        description: "Timestamp when the post was created."
      - name: favorite_count
        description: "Number of users who favorited the post."
      - name: last_activity_date
        description: "Timestamp of the last activity on the post."
      - name: last_edit_date
        description: "Timestamp of the last edit on the post."
      - name: last_editor_display_name
        description: "Display name of the user who last edited the post."
      - name: last_editor_user_id
        description: "User ID of the person who last edited the post."
      - name: owner_display_name
        description: "Name of the user who created the post."
      - name: owner_user_id
        description: "User ID of the creator of the post."
      - name: parent_id
        description: "ID of the parent post."
      - name: post_type_id
        description: "Type of post."
      - name: score
        description: "Score of the post."
      - name: tags
        description: "Tags associated with the post."
      - name: view_count
        description: "Number of times the post has been viewed."
  - name: fact_file
    description: "Model for StackOverflow tags (topics)"
    columns:
      - name: tag
        description: "Name of the tag"
        tests:
          - not_null
          - unique
      - name: total_questions
        description: "Total number of questions per tag"
        tests:
          - not_null 
      - name: unanswered_questions
        description: "Number of questions without any response"
      - name: unanswered_ratio
        description: "Ratio of unanswered questions (unanswered_questions / total_questions)"
      - name: avg_answers
        description: "Average of answers"
      - name: no_accepted_answer
        description: "Number of questions with unaccepted answers"
      - name: no_accepted_ratio
        description: "Ratio of questions with unaccepted answers (no_accepted_answer / total_questions)"
