models:
  - name: so_file
    description: "Staging model for StackOverflow tags (topics)"
    columns:
      - name: tag_name
        description: "Name of the tag"
        tests:
          - not_null
          - unique
      - name: total_questions
        description: "Total number of questions per tag"
        tests:
          - not_null 
      - name: unanswered_questions
        description: "Number of questions without any response"
      - name: unanswered_ratio
        description: "Ratio of unanswered questions (unanswered_questions / total_questions)"
      - name: avg_answers
        description: "Average of answers"
      - name: no_accepted_answer
        description: "Number of questions with unaccepted answers"
      - name: no_accepted_ratio
        description: "Ratio of questions with unaccepted answers (no_accepted_answer / total_questions)"
